# docker build -f dockerfile_replica -t midsc_replica .
# docker run -p 3523:3523 midsc_replica
FROM python:3.7.3
MAINTAINER llpinokio
WORKDIR /
RUN mkdir -p midsc
COPY ./ /midsc/
RUN pip install --upgrade pip && pip install -r midsc/requirements.txt
WORKDIR /midsc/src/
EXPOSE 3523
CMD ["./replica.py","-s"]